### ISSUE TITLE
Multiplayer host does not give feedback on error

### ISSUE THREAD

**Issue by xackery** [fornclake/TetraForce#107]

**Comment by fornclake** [comment]
regression, I redid the menus today and didn't reimplement the status label

**Comment by xackery** [comment]
E 0:00:20.629   rpcp: RPC '_receive_my_player_data' on yourself is not allowed by selected mode.
  <C++ Error>   Condition "skip_rpc && !(call_local_native || call_local_script)" is true.
  <C++ Source>  core/io/multiplayer_api.cpp:706 @ rpcp()
  <Stack Trace> network.gd:41 @ initialize()
                main.gd:42 @ start_game()
                main.gd:59 @ host_server()
                main.gd:119 @ _on_host_pressed()
