### ISSUE TITLE
Pushable blocks after mini boss room area title

### ISSUE THREAD

**Issue by xackery** [fornclake/TetraForce#135]

**Comment by IQGobo** [comment]
I think those are already implemented. There is a pushable block in the game.

**Comment by josephbmanley** [comment]
This may be for level design? It's unclear.

@rdg922 @fornclake @Elginive Can someone add a description to this issue? Thanks!

**Comment by rdg922** [comment]
We need another sprite for the push-able blocks to be in theme with the dungeon. AFAIK, these will be barrels

**Comment by josephbmanley** [comment]
@rdg922 Says dupe in discord
