### ISSUE TITLE
Small cannon

### ISSUE THREAD

**Issue by xackery** [fornclake/TetraForce#153]
with fuse that can be slashed. fires a cannonball that breaks a wall They rocket towards the player’s direction, and can’t be hurt, but they can’t change direction in the middle of them firing.

**Comment by xackery** [comment]
![blue_cannon](https://user-images.githubusercontent.com/845670/90223788-8cdee300-ddc3-11ea-93a4-444524a826ba.png)
for fun threw this together, what do you think?

**Comment by xackery** [comment]
![cannon_ball](https://user-images.githubusercontent.com/845670/90224161-1a223780-ddc4-11ea-8acc-8e5a46b7d7ac.png)
#154  is similar

**Comment by xackery** [comment]
![blue_cannon_fuse](https://user-images.githubusercontent.com/845670/90224539-ab91a980-ddc4-11ea-9f12-29a8621a5bf4.png)
fuse version

**Comment by Elginive** [comment]
Cannons are now implemented
