### ISSUE TITLE
Improper Tiles Used on Overworld Map

### ISSUE THREAD

**Issue by rdg922** [fornclake/TetraForce#186]
Currently known instances of clipping / wrong tiles being used:

- [ ] You can clip into the roof of the barn from the west field
![](https://cdn.discordapp.com/attachments/767452492870844417/767456037225103390/tf_bug_noclip_topofbarn.png)

- [ ] the bushes in the maze on the shore are blocking, cannot be slashed
![](https://cdn.discordapp.com/attachments/767452492870844417/767456209217257512/tf_bug_blockingbushes_southshoreswamp.png)

- [ ]  the grass tiles and bushes south of my position on the south shore here are blocking, off limits
![](https://cdn.discordapp.com/attachments/767452492870844417/767456392407285810/tf_bug_clipping_southshoreswamp_bothrowsbelow.png)

**Comment by Elginive** [comment]
These have now all been resolved.
