### ISSUE TITLE
Pulling Up Menu and Interact breaks dialogue 

### ISSUE THREAD

**Issue by rdg922** [fornclake/TetraForce#187]
![](https://cdn.discordapp.com/attachments/767452492870844417/767837613687832616/unknown.png)

Press enter & interact at the same time, it'll pull up the inventory. close the inventory, talk again, and you can walk away with dialogue stuck on your screen

**Comment by josephbmanley** [comment]
@rdg922 I am not able to replicate this issue. Do you know if it has been fixed within the last five days?

**Comment by rdg922** [comment]
I haven't been able to either. If it pops up I'll open the issue again but I think it's solved
