### ISSUE TITLE
Parallel Universes on Beach Scene

### ISSUE THREAD

**Issue by rdg922** [fornclake/TetraForce#192]
When two players walk into the beach at the same time two different instances occur, causing players to not see each other:

![](https://cdn.discordapp.com/attachments/688955131277869114/769621233032757268/unknown.png)

![](https://cdn.discordapp.com/attachments/688955131277869114/769621252050124820/unknown.png)

^^^ Pictures taken at the same time.

**Comment by josephbmanley** [comment]
Seems to load two maps for whatever reason at this location: 
![image](https://user-images.githubusercontent.com/21203171/97090997-7dbbb300-1606-11eb-99e7-87f4bb14a60e.png)

Currently still investigating cause, perhaps something in Tiled?

**Comment by rdg922** [comment]
Solution created and in the works: #193

**Comment by rdg922** [comment]
Fornclake implemented this in one of his streams I believe
