### ISSUE TITLE
Top of Entrance gates do not hide the player.

### ISSUE THREAD

**Issue by Zach777** [fornclake/TetraForce#215]
This gate should be hiding the player. From what I think the perspective implies anyway.
![StandingOnGateBug](https://user-images.githubusercontent.com/27028216/103705976-01383f80-4f7a-11eb-97be-3a9d26813aa0.png)

**Comment by rdg922** [comment]
This is odd, I know for a fact this used to work! @fornclake, do you know when this issue arose?

**Comment by fornclake** [comment]
It might've been recent, I don't think I saw that in my latest build.
Andrew was having issues with z index in the last few days, might be related

**Comment by Elginive** [comment]
I'm pretty sure the problem is from the Dec. 7th Merge. It just took awhile to show itself because I hadn't tried to re-import any maps from Tiled since that push
