### ISSUE TITLE
Upgrade project to Godot 3.3.2

### ISSUE THREAD

**Issue by josephbmanley** [fornclake/TetraForce#237]
**Description**

Currently, the project is 3.2.x, but we should upgrade to be able to use latest Godot features
@Nodding

**Comment by Nodding** [comment]
Testing with 3.3.2. Walking around map seems perfectly fine. Got an error unrelated to 3.3.2. Let us switch to 3.3.2 for the time being, and if anything 3.3.2 related happens, it is so my fault guys.

**Comment by josephbmanley** [comment]
If you're taking all responsibility, I'll close it.
