### ISSUE TITLE
Blue Cannon no longer able to fire and does not break wall for all players

### ISSUE THREAD

**Issue by josephbmanley** [fornclake/TetraForce#238]
![image](https://user-images.githubusercontent.com/21203171/119408218-5d92c600-bcb3-11eb-87cd-11110cef58c0.png)

**OS:**

Linux, Windows, and Server

**Issue description:**

Seems to be somewhat of a desync error. Maybe server has different data than client?

**Steps to reproduce:**

Join two player server, one fires cannon, it may or may not work.

**Comment by Nodding** [comment]
This error appears sometimes right as the cannon gets stuck. 
SCRIPT ERROR: interact: Invalid get index 'spritedir' (on base: 'EncodedObjectAsID').
          At: res://tiles/blue_cannon.gdc:19
![image](https://user-images.githubusercontent.com/32770553/119408801-4bfdee00-bcb4-11eb-9450-107f3fa31a3d.png)
