### ISSUE TITLE
Dead Players Not Updating

### ISSUE THREAD

**Issue by Nodding** [fornclake/TetraForce#33]
This dude can not die. I would imagine we would move the player back to spawn, and restore their health. Booting to the lobby may be too harsh.

**Comment by rmgr** [comment]
I think this is an interesting point which we should consider the consequences of early. Do we bounce him to the beginning of the scene? Or should we have like a temple of time-esque location where players respawn? I like the *idea* of the temple of time spawn point but I see that being annoying after a while.

If we do go down that route I think it will be important to make town somewhere you enjoy being. Lots of NPCs to interact with, lots of secrets to find, that kind of thing.

**Comment by fornclake** [comment]
If we put them in the beginning of the scene, then there isn't much punishment for death as if everyone is in the same dungeon all the time then none of the enemies/puzzles will respawn.

I'm leaning towards the temple of time thing too. If someone dies they have to return all the way back. If everyone dies, the dungeon enemies respawn. I'm not against having warps in front of or somewhat close to dungeons to mitigate this though.

**Comment by marcJV** [comment]
Another option could be a revive mechanic.

One option for this would be a player gives the dead player one of their hearts.

Another option is like the revive mechanic from castle crashers where a player is stuck doing a quick time event of sorts to give them health. This puts them in danger while trying to revive them.

This is just some spitballing and I'm open to any of the above options

**Comment by rmgr** [comment]
I really like that heart idea, that's pretty cool! Maybe at a 2:1 ratio or something though to give it a tangible cost.

**Comment by rdg922** [comment]
This is now an issue with syncing dead players
