### ISSUE TITLE
Godot 4+ Port.

### ISSUE THREAD

**Issue by WithinAmnesia** [fornclake/TetraForce#352]
Hello! I am new here and I noticed that this is in Godot 3 and I want to help it go to Godot 4+ to really help the community learn awesome / great multiplayer skills with a working and really cool demo. 

Goal: Tetra Force in Godot 4+ MIT license forever free with fully working multiplayer.

What are the details and what is there to look at / what is there to help with a Godot 4+ port of Tetra force? Also I'd like to add in Diablo / WoW style feature to the UI like inventory / loot with a separate experimental community dev tool set template version to keep all of my previous ARPG work together. Here are really good Diablo / WoW UI / Inventory / Loot systems made by a really talented person. This a sort of 2D / 3D hybrid sorta like this (really awesome rpg demo for Godot 4+): https://github.com/don-tnowe/godot-wyvernshield-triggers/tree/main (Also this is a really good one: https://github.com/don-tnowe/godot-wyvernbox-inventory Also these CC0 art assets are really awesome: https://foozlecc.itch.io/lucifer-exterior-tileset Also this inspiration for a 2D NES WoW MMORPG: https://www.youtube.com/watch?v=64oDMp0FGxA

I can also be found here: https://github.com/WithinAmnesia/ARPG + https://github.com/WithinAmnesia/ARPG/discussions/16

I am also trying to help build a working zone to zone travel patch to help the community with JDungeon: https://godotforums.org/d/40502-how-to-teleport-travel-to-another-scene-with-godot-4-multiplayer/ + https://github.com/jonathaneeckhout/jdungeon

What is needed for a Godot 4+ port and where could I start helping the most? All feedback is welcome. This is really awesome and I wish it gets better and better bit by bit.

**Comment by Elginive** [comment]
Hi WithinAmnesia! This project hasn't been active since 2022 unfortunately. Our Main dev had to step down, and without someone who has a strong GDSCript Language knowledge, it was hard to keep this project going. We had a really talented cloud dev on our team also, who is still around. I was the second Dev, but mostly the artist / animator for this game. I'd be happy to discuss with you, if you haven't already, join our discord (https://discord.gg/pk427kD3f2) - and message me privately. I'm happy to talk.

Regards,

**Comment by WithinAmnesia** [comment]
> Hi WithinAmnesia! This project hasn't been active since 2022 unfortunately. Our Main dev had to step down, and without someone who has a strong GDSCript Language knowledge, it was hard to keep this project going. We had a really talented cloud dev on our team also, who is still around. I was the second Dev, but mostly the artist / animator for this game. I'd be happy to discuss with you, if you haven't already, join our discord (https://discord.gg/pk427kD3f2) - and message me privately. I'm happy to talk.
> 
> Regards,

Hello! I have joined the Tetra Force Discord and I am here lol. I have already begun the preliminary Tetra Force Godot 4.2.1.NET+ Port. Well experimental versions to work iterations of progress bit by bit to try and keep things together as a conservative / preservative Godot 4+ port.
