### ISSUE TITLE
If two players appear on the same spot, they can't move

### ISSUE THREAD

**Issue by losfroger** [fornclake/TetraForce#55]
When two players appear on the same spot, neither of them can move and get stuck together. It can happen when the host player starts the game and hasn’t moved, and a second player joins in.

**Comment by fornclake** [comment]
This is a big one. Also happens if two people try moving to a different map and the first doesn't move after the transition.

**Comment by losfroger** [comment]
Oh yeah, it could also happen during a map change

**Comment by marcJV** [comment]
How do we want to tackle this?

Currently in the master branch if two players load in on top of each other, they will push apart/move to the left wall, but I don't know how it works with more than two.

Possibile solutions:
1. Turn off collision detection for other players forever, this would stop some griefing, but may cause other issues later on with items.
2. Have a 'safe area' or lobby for each new map when loading in where there is no collision detection between players. This could be just one room or the town, but once they are in the proper map then they will collide again.
3. Disable collision detection between players once they load in, and once they are not overlapping then enable collision between players again.

**Comment by rmgr** [comment]
I like the lobby idea. It could tie in with my proposal for a temple of time-esque area in #33
