### ISSUE TITLE
Leever/Wormlin Enemy

### ISSUE THREAD

**Issue by TerraDev64** [fornclake/TetraForce#57]
I'll implmement the Leever/Wormlin enemy into the game.

Here's a sprite made by me and polished by Elginive
![leever](https://user-images.githubusercontent.com/57131645/68102679-0d3af400-fed4-11e9-8598-8c95457dd902.png)

The behaviors are: 
* Moves invisibly underground toward a player, when it is near the player it emerges from the ground and continues pursuing the player for a short time before dropping back underground

* While underground and in transition it does not deal damage and cannot take damage

If you have some ideas to make this enemy look better please tell me.

I plan to implement this little lovely thing in the end of the week, but maybe will need assistance because I never wrote an Enemy AI and especially not for such a special behavior.

**Comment by RedstoneParadox** [comment]
Probably shouldn't call it the Leever.

**Comment by TerraWest64** [comment]
Any Ideas for names?

**Comment by rmgr** [comment]
We could just go generic and go with worm or mole or something

**Comment by TerraWest64** [comment]
maybe but sounds boring IMO

**Comment by Nodding** [comment]
Maybe "Wriggler" makes my skin crawl just saying it. A play on "Wiggler" from Mario.

**Comment by lelanophilus** [comment]
What about "Wrigglorn"? Or maybe that is too pokemon of a name.

**Comment by RedstoneParadox** [comment]
One of the suggestions on discord was Wormlion, which could open up some sort of roar mechanics (since, you know, lions roar and it's a Worm***lion***)

**Comment by rmgr** [comment]
> One of the suggestions on discord was Wormlion, which could open up some sort of roar mechanics (since, you know, lions roar and it's a Worm_**lion**_)

I like Wormlion! Introducing some sort of roar mechanic would also go a long way towards not being Zelda and therefore not getting shut down!

**Comment by TerraWest64** [comment]
Ok so, after some suggestions I'll stick to Wormlin.
IF someone really does not agree with it, tell me
