### ISSUE TITLE
Names should have a character cap that matches the length of a rendered name

### ISSUE THREAD

**Issue by valorcrafting** [fornclake/TetraForce#65]
In testing, I entered my non-abbreviated username. This was the result:
![issueName](https://user-images.githubusercontent.com/29130973/68534716-3d7ff980-02fd-11ea-9c33-26c38729d262.PNG)
I think the way to fix this may be to add a character cap that matches the length of the longest name that can be rendered.

**Comment by IQGobo** [comment]
We have pull request #66 for that, but maybe we should be more restrictive on the character select screen and just set a max length.
