### ISSUE TITLE
Bombable walls have a greater hitbox than other walls

### ISSUE THREAD

**Issue by marcJV** [fornclake/TetraForce#69]
You can get stuck on a bombable wall if  you walk along the wall

Reproduction steps:
Find a bombable wall
Move and touch a wall close to bombable wall tile, but not on it
Move towards the bombable wall
Player will get stuck from moving along the wall.

![ScreenRecording2019-11-11at10283](https://user-images.githubusercontent.com/1293444/68642327-66f27e00-04d3-11ea-971c-b26f638ef436.gif)

**Comment by rmgr** [comment]
I'm not gonna lie there is a chance that I've left the collision box huge from when I was debugging something... I can check tonight unless someone wants to have a look
