### ISSUE TITLE
Push block door

### ISSUE THREAD

**Issue by fornclake** [fornclake/TetraForce#8]
Door that only opens if a specific block in a dungeon has been pushed. No art for blocks yet so simple programmer art is sufficient (unless you wanna draw something)

You can probably check if the player's push animation is playing for a certain amount of time against the block. Count how long a player is colliding with the block, and then move it when it reaches a threshold.

I don't think we have door sprites either, if you wanna do this ask in the Discord.

**Comment by fornclake** [comment]
Really the push block by itself is pretty important for puzzles. All it needs to do is check if the player is pushing for a second and then move one space and one space only. It can reset when off screen with a home_position.

**Comment by programaths** [comment]
I am trying to do that one, but without the networking part.

**Comment by programaths** [comment]
Also, I would add "number of moves" for the block and a "block detector".
Then the block detector could be connected to a door and "trigger" it.

**Comment by programaths** [comment]
I have an issue with enemies who do not honor the collision: https://youtu.be/ytpNt9KTvag

**Comment by fornclake** [comment]
Enemies are on a different collision layer than players and arrows, so assuming it's a static body 2d (haven't looked yet, in class), you can just add collision layer and mask bit 1 to them.

Bit 1 being the second box in the Inspector. Bit 0 is selected by default.

**Comment by fornclake** [comment]
Oh right. Well all body nodes can change collision layers. If you don't find it yourself I'll put a comment on your PR when I get home.

**Comment by programaths** [comment]
I found, I will PR it
