### ISSUE TITLE
Controls configuration always shows Nintendo button names

### ISSUE THREAD

**Issue by DanielMcPherson** [fornclake/TetraForce#81]
The window (opened with the Shift key) that configures the weapons controls always shows Nintendo button names. This is confusing when using an Xbox controller or the keyboard.

XBox buttons A, X, Y, B map to Nintendo buttons B, Y, X, A. When using the keyboard, "B" is shown for the C key, "X" for the V key, and "Y" for the B key.

If possible, detect the type controller being used and show Xbox button names when an Xbox controller is being used. If configuring controls using the keyboard, show the keyboard key that was pressed.

**Comment by rmgr** [comment]
This looks like it'll be fairly straight-forward to implement judging by this [thread](https://godotengine.org/qa/17892/check-if-controller-connected-or-not).

**Comment by M0LD** [comment]
A manual selection of what controller your using is also something that could be done, like in enter the gungeon
