### ISSUE TITLE
Slime Enemy

### ISSUE THREAD

**Issue by rmgr** [fornclake/TetraForce#82]
I'm working on slimes. If anybody wants to do some slime art for me please feel free! ;)

![slimes_more_slimey_behaviour](https://user-images.githubusercontent.com/6480274/68743016-6841b900-0641-11ea-8281-b4b2677dea33.gif)

**Comment by Hairic95** [comment]
started on it, currently made the basic idle animation in 3 colors.
TODO//
hint/prepare to attack animation
dash animation
doing a 32x32 version for a miniboss
