### ISSUE TITLE
Cutting bushes

### ISSUE THREAD

**Issue by fornclake** [fornclake/TetraForce#9]
We have bush tiles in the overworld tileset. Now we need to be able to cut them. They will probably be objects and would be added to the object_placer. No leaf particles just yet.

**Comment by Levrault** [comment]
I think I could be able to implement this on the singleplayer side.

**Comment by Levrault** [comment]
Hi, I made a first naive implementation but I ain't got right to create a new branch on the project. Could you add me please ?

I also got a few questions to improve the "destroy thing" process for the future.

It seems that the player hitbox isn't based on collision or mask layer (correct me if I'm wrong). could it be a good idear to name those layer in the project settings and set specific collision mask for the sword ?

Thanks
